<?php
/** Settings screens: URL slug => [title, permission, icon, intro, fields]. Every key is saved to the settings table. */

$fonts = array_combine(font_options(), font_options());
$tz = array_combine(DateTimeZone::listIdentifiers(), DateTimeZone::listIdentifiers());

return [
    'general' => ['General settings', 'settings.general', 'settings', 'Site identity, logos and regional settings.', [
        ['name' => 'site_name', 'label' => 'Website name', 'type' => 'text', 'rules' => 'required|max:80', 'width' => 'half'],
        ['name' => 'tagline', 'label' => 'Tagline', 'type' => 'text', 'rules' => 'max:160', 'width' => 'half'],
        ['name' => 'logo_desktop', 'label' => 'Desktop logo', 'type' => 'image', 'width' => 'third', 'help' => 'SVG or PNG on a transparent background. Empty = text logo.'],
        ['name' => 'logo_mobile', 'label' => 'Mobile logo', 'type' => 'image', 'width' => 'third', 'help' => 'Optional. Defaults to the desktop logo.'],
        ['name' => 'favicon', 'label' => 'Favicon', 'type' => 'image', 'width' => 'third', 'help' => 'Square PNG/SVG, at least 64 × 64 px.'],
        ['name' => 'timezone', 'label' => 'Timezone', 'type' => 'select', 'options' => $tz, 'rules' => 'required', 'width' => 'half', 'help' => 'Used for dates on the website and in the panel.'],
        ['name' => 'copyright_text', 'label' => 'Copyright line', 'type' => 'text', 'rules' => 'max:200', 'width' => 'half', 'help' => '{year} is replaced with the current year.'],
        ['name' => 'media_max_mb', 'label' => 'Maximum upload size (MB)', 'type' => 'number', 'rules' => 'required|between:1,20', 'width' => 'half'],
        ['name' => 'maintenance_mode', 'label' => 'Maintenance mode (public site shows a “back soon” page; the Control Panel keeps working)', 'type' => 'checkbox'],
        ['name' => 'maintenance_message', 'label' => 'Maintenance message', 'type' => 'text', 'rules' => 'max:255'],
    ]],
    'contact-details' => ['Contact details', 'settings.general', 'phone', 'Shown in the footer, contact page and structured data. Leave empty anything you do not want to publish.', [
        ['name' => 'contact_email', 'label' => 'Email', 'type' => 'email', 'rules' => 'email|max:190', 'width' => 'half'],
        ['name' => 'contact_phone', 'label' => 'Phone', 'type' => 'text', 'rules' => 'phone|max:40', 'width' => 'half'],
        ['name' => 'contact_whatsapp', 'label' => 'WhatsApp number', 'type' => 'text', 'rules' => 'phone|max:40', 'width' => 'half', 'help' => 'International format, e.g. +44 7700 900000'],
        ['name' => 'notify_email', 'label' => 'Send form notifications to', 'type' => 'email', 'rules' => 'email|max:190', 'width' => 'half', 'help' => 'Defaults to the contact email.'],
        ['name' => 'contact_address', 'label' => 'Address', 'type' => 'textarea', 'rules' => 'max:500', 'rows' => 3, 'width' => 'half'],
        ['name' => 'business_hours', 'label' => 'Business hours', 'type' => 'textarea', 'rules' => 'max:300', 'rows' => 3, 'width' => 'half'],
        ['name' => 'map_embed_url', 'label' => 'Google Maps embed URL', 'type' => 'text', 'rules' => 'max:1000', 'help' => 'Google Maps → Share → Embed a map → copy only the src="…" address (starts with https://www.google.com/maps/embed?).'],
        ['name' => 'contact_heading', 'label' => 'Contact page heading', 'type' => 'text', 'rules' => 'max:160', 'width' => 'half', 'tab' => 'Contact page'],
        ['name' => 'contact_eyebrow', 'label' => 'Contact page eyebrow', 'type' => 'text', 'rules' => 'max:60', 'width' => 'half', 'tab' => 'Contact page'],
        ['name' => 'contact_intro', 'label' => 'Contact page intro', 'type' => 'textarea', 'rules' => 'max:600', 'rows' => 3, 'tab' => 'Contact page'],
        ['name' => 'contact_success', 'label' => 'Success message', 'type' => 'text', 'rules' => 'max:300', 'tab' => 'Contact page'],
        ['name' => 'contact_send_confirmation', 'label' => 'Email a confirmation to the visitor', 'type' => 'checkbox', 'tab' => 'Contact page'],
        ['name' => 'booking_heading', 'label' => 'Booking page heading', 'type' => 'text', 'rules' => 'max:160', 'width' => 'half', 'tab' => 'Booking page'],
        ['name' => 'booking_eyebrow', 'label' => 'Booking page eyebrow / menu name', 'type' => 'text', 'rules' => 'max:60', 'width' => 'half', 'tab' => 'Booking page'],
        ['name' => 'booking_intro', 'label' => 'Booking page intro', 'type' => 'textarea', 'rules' => 'max:600', 'rows' => 3, 'tab' => 'Booking page'],
        ['name' => 'booking_points', 'label' => '“What we will cover” (one per line)', 'type' => 'textarea', 'rules' => 'max:1000', 'rows' => 4, 'tab' => 'Booking page'],
        ['name' => 'booking_consent_text', 'label' => 'Consent checkbox text', 'type' => 'text', 'rules' => 'max:300', 'tab' => 'Booking page'],
        ['name' => 'booking_success', 'label' => 'Success message', 'type' => 'text', 'rules' => 'max:300', 'tab' => 'Booking page'],
        ['name' => 'booking_send_confirmation', 'label' => 'Email a confirmation to the visitor', 'type' => 'checkbox', 'tab' => 'Booking page'],
        ['name' => 'services_eyebrow', 'label' => 'Services page eyebrow', 'type' => 'text', 'rules' => 'max:60', 'width' => 'half', 'tab' => 'Listing pages'],
        ['name' => 'services_heading', 'label' => 'Services page heading', 'type' => 'text', 'rules' => 'max:160', 'width' => 'half', 'tab' => 'Listing pages'],
        ['name' => 'services_intro', 'label' => 'Services page intro', 'type' => 'textarea', 'rules' => 'max:600', 'rows' => 3, 'tab' => 'Listing pages'],
        ['name' => 'blog_eyebrow', 'label' => 'Blog eyebrow', 'type' => 'text', 'rules' => 'max:60', 'width' => 'half', 'tab' => 'Listing pages'],
        ['name' => 'blog_heading', 'label' => 'Blog heading', 'type' => 'text', 'rules' => 'max:160', 'width' => 'half', 'tab' => 'Listing pages'],
        ['name' => 'blog_intro', 'label' => 'Blog intro', 'type' => 'textarea', 'rules' => 'max:600', 'rows' => 3, 'tab' => 'Listing pages'],
    ]],
    'header' => ['Header', 'settings.general', 'menu', 'Header behaviour, call-to-action button and announcement bar. Menu links are managed under Navigation.', [
        ['name' => 'header_cta_enabled', 'label' => 'Show header button', 'type' => 'checkbox'],
        ['name' => 'header_cta_label', 'label' => 'Button text', 'type' => 'text', 'rules' => 'max:40', 'width' => 'half'],
        ['name' => 'header_cta_url', 'label' => 'Button link', 'type' => 'link', 'rules' => 'max:500', 'width' => 'half'],
        ['name' => 'header_secondary_label', 'label' => 'Secondary link text (optional)', 'type' => 'text', 'rules' => 'max:40', 'width' => 'half', 'help' => 'e.g. “Sign in” linking to your app.'],
        ['name' => 'header_secondary_url', 'label' => 'Secondary link', 'type' => 'link', 'rules' => 'max:500', 'width' => 'half'],
        ['name' => 'header_sticky', 'label' => 'Sticky header', 'type' => 'checkbox', 'width' => 'half'],
        ['name' => 'header_transparent_home', 'label' => 'Transparent over the homepage hero', 'type' => 'checkbox', 'width' => 'half'],
        ['name' => 'announcement_enabled', 'label' => 'Show announcement bar', 'type' => 'checkbox', 'tab' => 'Announcement'],
        ['name' => 'announcement_text', 'label' => 'Announcement text', 'type' => 'text', 'rules' => 'max:200', 'tab' => 'Announcement'],
        ['name' => 'announcement_url', 'label' => 'Announcement link (optional)', 'type' => 'link', 'rules' => 'max:500', 'tab' => 'Announcement'],
    ]],
    'footer' => ['Footer', 'settings.general', 'section', 'Footer content and columns. Column links are managed under Navigation (Footer column 1–3).', [
        ['name' => 'footer_about', 'label' => 'About text', 'type' => 'textarea', 'rules' => 'max:500', 'rows' => 3],
        ['name' => 'footer_col1_title', 'label' => 'Column 1 title', 'type' => 'text', 'rules' => 'max:40', 'width' => 'third'],
        ['name' => 'footer_col2_title', 'label' => 'Column 2 title', 'type' => 'text', 'rules' => 'max:40', 'width' => 'third'],
        ['name' => 'footer_col3_title', 'label' => 'Column 3 title', 'type' => 'text', 'rules' => 'max:40', 'width' => 'third'],
        ['name' => 'footer_show_services', 'label' => 'Column 1 lists published services automatically', 'type' => 'checkbox'],
        ['name' => 'footer_show_contact', 'label' => 'Show contact details', 'type' => 'checkbox', 'width' => 'half'],
        ['name' => 'footer_show_social', 'label' => 'Show social icons', 'type' => 'checkbox', 'width' => 'half'],
        ['name' => 'footer_cta_enabled', 'label' => 'Show call-to-action band', 'type' => 'checkbox', 'tab' => 'Call to action'],
        ['name' => 'footer_cta_heading', 'label' => 'Heading', 'type' => 'text', 'rules' => 'max:160', 'tab' => 'Call to action'],
        ['name' => 'footer_cta_text', 'label' => 'Text', 'type' => 'text', 'rules' => 'max:300', 'tab' => 'Call to action'],
        ['name' => 'footer_cta_label', 'label' => 'Button text', 'type' => 'text', 'rules' => 'max:40', 'width' => 'half', 'tab' => 'Call to action'],
        ['name' => 'footer_cta_url', 'label' => 'Button link', 'type' => 'link', 'rules' => 'max:500', 'width' => 'half', 'tab' => 'Call to action'],
        ['name' => 'footer_disclaimer', 'label' => 'Disclaimer / risk warning', 'type' => 'textarea', 'rules' => 'max:1500', 'rows' => 4, 'tab' => 'Legal'],
    ]],
    'social' => ['Social links', 'settings.general', 'globe', 'Full profile URLs. Empty links are hidden. Used in the footer and Organization structured data.', [
        ['name' => 'social_x', 'label' => 'X (Twitter)', 'type' => 'text', 'rules' => 'url|max:300', 'width' => 'half'],
        ['name' => 'social_linkedin', 'label' => 'LinkedIn', 'type' => 'text', 'rules' => 'url|max:300', 'width' => 'half'],
        ['name' => 'social_youtube', 'label' => 'YouTube', 'type' => 'text', 'rules' => 'url|max:300', 'width' => 'half'],
        ['name' => 'social_instagram', 'label' => 'Instagram', 'type' => 'text', 'rules' => 'url|max:300', 'width' => 'half'],
        ['name' => 'social_facebook', 'label' => 'Facebook', 'type' => 'text', 'rules' => 'url|max:300', 'width' => 'half'],
        ['name' => 'social_discord', 'label' => 'Discord', 'type' => 'text', 'rules' => 'url|max:300', 'width' => 'half'],
        ['name' => 'social_telegram', 'label' => 'Telegram', 'type' => 'text', 'rules' => 'url|max:300', 'width' => 'half'],
        ['name' => 'social_github', 'label' => 'GitHub', 'type' => 'text', 'rules' => 'url|max:300', 'width' => 'half'],
    ]],
    'whatsapp' => ['WhatsApp', 'settings.whatsapp', 'whatsapp', 'Floating WhatsApp chat button.', [
        ['name' => 'whatsapp_enabled', 'label' => 'Show the WhatsApp button', 'type' => 'checkbox'],
        ['name' => 'whatsapp_number', 'label' => 'WhatsApp number', 'type' => 'text', 'rules' => 'phone|max:40', 'width' => 'half', 'help' => 'International format with country code. Empty = the contact WhatsApp number.'],
        ['name' => 'whatsapp_label', 'label' => 'Button label', 'type' => 'text', 'rules' => 'max:40', 'width' => 'half'],
        ['name' => 'whatsapp_message', 'label' => 'Default message', 'type' => 'textarea', 'rules' => 'max:300', 'rows' => 2],
        ['name' => 'whatsapp_position', 'label' => 'Position', 'type' => 'select', 'options' => ['right' => 'Bottom right', 'left' => 'Bottom left'], 'width' => 'third'],
        ['name' => 'whatsapp_mobile', 'label' => 'Show on mobile', 'type' => 'checkbox', 'width' => 'third'],
        ['name' => 'whatsapp_desktop', 'label' => 'Show on desktop', 'type' => 'checkbox', 'width' => 'third'],
    ]],
    'seo' => ['SEO', 'settings.seo', 'search', 'Global search and social metadata. Pages, services and posts have their own SEO fields.', [
        ['name' => 'seo_default_title', 'label' => 'Default / homepage title', 'type' => 'text', 'rules' => 'max:120', 'counter' => 60],
        ['name' => 'seo_default_description', 'label' => 'Default meta description', 'type' => 'textarea', 'rules' => 'max:320', 'rows' => 3, 'counter' => 160],
        ['name' => 'seo_title_separator', 'label' => 'Title separator', 'type' => 'select', 'options' => ['|' => '|', '—' => '—', '-' => '-', '·' => '·'], 'width' => 'third'],
        ['name' => 'seo_robots', 'label' => 'Default robots', 'type' => 'select', 'options' => ['index, follow' => 'index, follow', 'index, nofollow' => 'index, nofollow', 'noindex, follow' => 'noindex, follow', 'noindex, nofollow' => 'noindex, nofollow'], 'width' => 'third'],
        ['name' => 'seo_allow_indexing', 'label' => 'Allow search engines to index this site', 'type' => 'checkbox', 'width' => 'third', 'help' => 'Untick on staging sites.'],
        ['name' => 'seo_canonical_base', 'label' => 'Canonical base URL', 'type' => 'text', 'rules' => 'url|max:200', 'help' => 'Optional, e.g. https://journzey.ai — used for canonical tags and the sitemap. Defaults to BASE_URL.'],
        ['name' => 'seo_og_title', 'label' => 'Default OG title', 'type' => 'text', 'rules' => 'max:120', 'tab' => 'Social sharing', 'width' => 'half'],
        ['name' => 'seo_twitter_site', 'label' => 'X/Twitter handle', 'type' => 'text', 'rules' => 'max:40', 'tab' => 'Social sharing', 'width' => 'half', 'help' => 'e.g. @journzey'],
        ['name' => 'seo_og_description', 'label' => 'Default OG description', 'type' => 'textarea', 'rules' => 'max:300', 'rows' => 2, 'tab' => 'Social sharing'],
        ['name' => 'seo_og_image', 'label' => 'Default OG image', 'type' => 'image', 'tab' => 'Social sharing', 'help' => '1200 × 630 px.'],
        ['name' => 'seo_twitter_card', 'label' => 'Twitter card', 'type' => 'select', 'options' => ['summary_large_image' => 'Large image', 'summary' => 'Summary'], 'tab' => 'Social sharing', 'width' => 'half'],
        ['name' => 'seo_home_title', 'label' => 'Homepage title override', 'type' => 'text', 'rules' => 'max:120', 'tab' => 'Page titles', 'width' => 'half'],
        ['name' => 'seo_home_description', 'label' => 'Homepage description override', 'type' => 'text', 'rules' => 'max:320', 'tab' => 'Page titles', 'width' => 'half'],
        ['name' => 'seo_services_title', 'label' => 'Services title', 'type' => 'text', 'rules' => 'max:120', 'tab' => 'Page titles', 'width' => 'half'],
        ['name' => 'seo_services_description', 'label' => 'Services description', 'type' => 'text', 'rules' => 'max:320', 'tab' => 'Page titles', 'width' => 'half'],
        ['name' => 'seo_blog_title', 'label' => 'Blog title', 'type' => 'text', 'rules' => 'max:120', 'tab' => 'Page titles', 'width' => 'half'],
        ['name' => 'seo_blog_description', 'label' => 'Blog description', 'type' => 'text', 'rules' => 'max:320', 'tab' => 'Page titles', 'width' => 'half'],
        ['name' => 'seo_contact_title', 'label' => 'Contact title', 'type' => 'text', 'rules' => 'max:120', 'tab' => 'Page titles', 'width' => 'half'],
        ['name' => 'seo_contact_description', 'label' => 'Contact description', 'type' => 'text', 'rules' => 'max:320', 'tab' => 'Page titles', 'width' => 'half'],
        ['name' => 'seo_booking_title', 'label' => 'Booking title', 'type' => 'text', 'rules' => 'max:120', 'tab' => 'Page titles', 'width' => 'half'],
        ['name' => 'seo_booking_description', 'label' => 'Booking description', 'type' => 'text', 'rules' => 'max:320', 'tab' => 'Page titles', 'width' => 'half'],
        ['name' => 'seo_schema_enabled', 'label' => 'Output Organization & WebSite structured data', 'type' => 'checkbox', 'tab' => 'Structured data & robots'],
        ['name' => 'seo_local_business', 'label' => 'Output LocalBusiness data (only if you have a real, public business address in Contact details)', 'type' => 'checkbox', 'tab' => 'Structured data & robots'],
        ['name' => 'seo_robots_extra', 'label' => 'Extra robots.txt rules', 'type' => 'textarea', 'rules' => 'max:2000', 'rows' => 4, 'tab' => 'Structured data & robots', 'help' => 'Added to the generated /robots.txt, e.g. “Disallow: /private”.'],
    ]],
    'analytics' => ['Analytics & tracking', 'settings.analytics', 'bars', 'Tracking codes are only output when enabled and the ID format is valid.', [
        ['name' => 'ga_enabled', 'label' => 'Enable Google Analytics 4', 'type' => 'checkbox', 'width' => 'half'],
        ['name' => 'ga_id', 'label' => 'Measurement ID', 'type' => 'text', 'rules' => 'max:30', 'width' => 'half', 'help' => 'e.g. G-XXXXXXXXXX'],
        ['name' => 'gtm_enabled', 'label' => 'Enable Google Tag Manager', 'type' => 'checkbox', 'width' => 'half'],
        ['name' => 'gtm_id', 'label' => 'Container ID', 'type' => 'text', 'rules' => 'max:30', 'width' => 'half', 'help' => 'e.g. GTM-XXXXXXX'],
        ['name' => 'pixel_enabled', 'label' => 'Enable Meta Pixel', 'type' => 'checkbox', 'width' => 'half'],
        ['name' => 'pixel_id', 'label' => 'Pixel ID', 'type' => 'text', 'rules' => 'max:30', 'width' => 'half', 'help' => 'Digits only.'],
        ['name' => 'gsc_enabled', 'label' => 'Enable Search Console verification', 'type' => 'checkbox', 'width' => 'half'],
        ['name' => 'gsc_code', 'label' => 'Verification code', 'type' => 'text', 'rules' => 'max:300', 'width' => 'half', 'help' => 'The content value of the google-site-verification meta tag (or the whole tag).'],
    ]],
    'appearance/colors' => ['Colours', 'appearance', 'palette', 'Brand and background colours used across the public website.', [
        ['name' => 'color_primary', 'label' => 'Primary', 'type' => 'color', 'rules' => 'required|color', 'width' => 'third'],
        ['name' => 'color_secondary', 'label' => 'Secondary', 'type' => 'color', 'rules' => 'required|color', 'width' => 'third'],
        ['name' => 'color_accent', 'label' => 'Accent (success)', 'type' => 'color', 'rules' => 'required|color', 'width' => 'third'],
        ['name' => 'color_heading', 'label' => 'Headings', 'type' => 'color', 'rules' => 'required|color', 'width' => 'third'],
        ['name' => 'color_text', 'label' => 'Body text', 'type' => 'color', 'rules' => 'required|color', 'width' => 'third'],
        ['name' => 'color_muted', 'label' => 'Muted text', 'type' => 'color', 'rules' => 'required|color', 'width' => 'third'],
        ['name' => 'color_bg', 'label' => 'Page background', 'type' => 'color', 'rules' => 'required|color', 'width' => 'third'],
        ['name' => 'color_surface', 'label' => 'Card / surface background', 'type' => 'color', 'rules' => 'required|color', 'width' => 'third'],
        ['name' => 'color_border', 'label' => 'Borders', 'type' => 'color', 'rules' => 'required|color', 'width' => 'third'],
    ]],
    'appearance/typography' => ['Typography', 'appearance', 'type', 'Fonts load from Google Fonts. “System” uses the visitor’s device font (fastest).', [
        ['name' => 'font_heading', 'label' => 'Heading font', 'type' => 'select', 'options' => $fonts, 'width' => 'half'],
        ['name' => 'font_body', 'label' => 'Body font', 'type' => 'select', 'options' => $fonts, 'width' => 'half'],
        ['name' => 'font_base_size', 'label' => 'Base font size (px)', 'type' => 'number', 'rules' => 'required|between:14,20', 'width' => 'half'],
        ['name' => 'heading_weight', 'label' => 'Heading weight', 'type' => 'select', 'options' => ['500' => 'Medium', '600' => 'Semibold', '700' => 'Bold'], 'width' => 'half'],
    ]],
    'appearance/buttons' => ['Buttons', 'appearance', 'zap', 'Button and corner style.', [
        ['name' => 'button_style', 'label' => 'Button shape', 'type' => 'select', 'options' => ['pill' => 'Pill', 'rounded' => 'Rounded', 'square' => 'Square'], 'width' => 'half'],
        ['name' => 'radius', 'label' => 'Card corner radius (px)', 'type' => 'number', 'rules' => 'required|between:0,32', 'width' => 'half'],
        ['name' => 'button_glow', 'label' => 'Glow on primary buttons', 'type' => 'checkbox', 'width' => 'half'],
        ['name' => 'button_uppercase', 'label' => 'Uppercase button text', 'type' => 'checkbox', 'width' => 'half'],
    ]],
    'appearance/layout' => ['Layout options', 'appearance', 'grid', 'Content width, spacing and motion.', [
        ['name' => 'container_width', 'label' => 'Content width (px)', 'type' => 'number', 'rules' => 'required|between:960,1600', 'width' => 'half'],
        ['name' => 'section_spacing', 'label' => 'Section spacing', 'type' => 'select', 'options' => ['compact' => 'Compact', 'normal' => 'Normal', 'spacious' => 'Spacious'], 'width' => 'half'],
        ['name' => 'animations_enabled', 'label' => 'Scroll reveal animations (always off for visitors who prefer reduced motion)', 'type' => 'checkbox'],
    ]],
    'appearance/custom-css' => ['Custom CSS', 'custom_css', 'code', 'Advanced: CSS added after the theme styles on every public page. Only roles with the Custom CSS permission can edit this.', [
        ['name' => 'custom_css', 'label' => 'Custom CSS', 'type' => 'code', 'rules' => 'max:50000'],
    ]],
];
