<?php
declare(strict_types=1);

namespace App\Trading;

use App\Core\Database;

/**
 * Daily "flex card": a shareable summary of one trading day (P&L, win rate, emotions, discipline score).
 * Each card gets a short public code; the QR code on the image opens /verify/{code}, which confirms the card
 * was generated by journzey.ai from that journal and shows the same figures (nothing more).
 */
final class FlexCard
{
    /** Builds (or refreshes) the card for a day and returns [payload, code]. */
    public static function forDay(array $m, array $acc, string $date, string $tz): array
    {
        $zone = new \DateTimeZone($tz);
        $from = (new \DateTimeImmutable($date . ' 00:00:00', $zone))->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s');
        $to = (new \DateTimeImmutable($date . ' 00:00:00', $zone))->modify('+1 day')->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s');
        $trades = Database::all(Ledger::TRADE_SELECT . " WHERE t.user_id = :u AND t.account_id = :a AND t.status = 'CLOSED' AND t.executed_at >= :f AND t.executed_at < :t ORDER BY t.executed_at",
            ['u' => $m['id'], 'a' => $acc['id'], 'f' => $from, 't' => $to]);
        $s = Analytics::summarize($trades);
        $entry = Database::one('SELECT * FROM journal_entries WHERE user_id = :u AND journal_date = :d AND is_demo = :x', ['u' => $m['id'], 'd' => $date, 'x' => (int) $acc['has_demo_data']]);
        $score = Journal::disciplineScore($entry, $trades, $m, $acc, $date, $tz);
        $emotions = [];
        if ($entry && $entry['emotional_state']) {
            $emotions[] = Domain::JOURNAL_EMOTIONS[$entry['emotional_state']] ?? ucfirst(strtolower($entry['emotional_state']));
        }
        foreach (array_count_values(array_filter(array_column($trades, 'emotion'))) as $em => $n) {
            $label = Domain::JOURNAL_EMOTIONS[$em] ?? ucfirst(strtolower((string) $em));
            if (!in_array($label, $emotions, true)) {
                $emotions[] = $label;
            }
        }
        $rs = array_values(array_filter(array_map(fn ($t) => $t['rr'] === null ? null : (float) $t['rr'], $trades), fn ($v) => $v !== null));
        $best = null;
        foreach ($trades as $t) {
            if ($best === null || (float) $t['pnl'] > (float) $best['pnl']) {
                $best = $t;
            }
        }
        $first = trim(explode(' ', trim((string) $m['name']))[0] ?? '');
        $payload = [
            'date' => $date, 'date_label' => (new \DateTimeImmutable($date))->format('D, j M Y'), 'name' => $first, 'currency' => $acc['currency'],
            'net' => round((float) $s['net'], 2), 'trades' => (int) $s['trades'], 'wins' => (int) $s['wins'], 'losses' => (int) $s['losses'],
            'win_rate' => $s['win_rate'], 'total_r' => $rs ? round(array_sum($rs), 2) : null,
            'best' => $best ? ['symbol' => $best['symbol'], 'pnl' => round((float) $best['pnl'], 2)] : null,
            'emotions' => array_slice($emotions, 0, 3), 'discipline' => $score ? $score['score'] : null,
            'rating' => $entry && $entry['discipline_rating'] !== null ? (int) $entry['discipline_rating'] : null,
            'lesson' => $entry && $entry['key_lesson'] ? mb_strimwidth((string) $entry['key_lesson'], 0, 90, '…') : null,
            'demo' => (int) $acc['has_demo_data'] === 1, 'account_type' => (int) $acc['is_demo'] ? 'Demo account' : 'Live account',
        ];
        $row = Database::one('SELECT code FROM share_cards WHERE user_id = :u AND account_id = :a AND card_date = :d', ['u' => $m['id'], 'a' => $acc['id'], 'd' => $date]);
        $code = $row['code'] ?? substr(strtr(base64_encode(random_bytes(9)), '+/', 'Kz'), 0, 12);
        Database::query('INSERT INTO share_cards (code, user_id, account_id, card_date, payload) VALUES (:c, :u, :a, :d, :p)
            ON DUPLICATE KEY UPDATE payload = VALUES(payload), updated_at = CURRENT_TIMESTAMP',
            ['c' => $code, 'u' => $m['id'], 'a' => $acc['id'], 'd' => $date, 'p' => json_encode($payload)]);
        return [$payload, $code];
    }

    /** Public lookup for the verification page. */
    public static function find(string $code): ?array
    {
        if (!preg_match('/^[A-Za-z0-9]{12}$/', $code)) {
            return null;
        }
        $row = Database::one('SELECT payload, created_at, updated_at FROM share_cards WHERE code = :c', ['c' => $code]);
        if (!$row) {
            return null;
        }
        return ['payload' => json_decode($row['payload'], true) ?: [], 'created_at' => $row['created_at'], 'updated_at' => $row['updated_at']];
    }
}
