<?php
declare(strict_types=1);

namespace App\Controllers;

use App\Core\Csrf;
use App\Core\Database;
use App\Core\Request;
use App\Core\Response;
use App\Core\View;
use PDO;

/**
 * One-time web installer at /setup. Writes config/config.php (with a random APP_KEY), imports database.sql
 * when the tables are missing and creates the first Super Admin. Afterwards it writes storage/installed.lock
 * and the route returns 404, so the installer cannot run again by accident.
 */
final class SetupController
{
    public function show(Request $req): never
    {
        $this->guard();
        $this->view(['state' => $this->state(), 'errors' => [], 'old' => []]);
    }

    public function install(Request $req): never
    {
        $this->guard();
        Csrf::verify($req);
        $state = $this->state();
        $errors = [];
        $in = fn (string $k) => trim((string) ($_POST[$k] ?? ''));
        $old = array_diff_key($_POST, ['db_pass' => 1, 'admin_password' => 1, 'admin_password_confirmation' => 1, '_csrf' => 1]);

        if ($state['admins'] > 0) {
            file_put_contents(INSTALL_LOCK, gmdate('c'));
            Response::redirect('/' . ADMIN_PREFIX . '/login');
        }

        // Admin account fields (always required).
        $name = $in('admin_name');
        $email = strtolower($in('admin_email'));
        $pass = (string) ($_POST['admin_password'] ?? '');
        if ($name === '' || mb_strlen($name) > 120) {
            $errors['admin_name'] = 'Enter your name.';
        }
        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            $errors['admin_email'] = 'Enter a valid email address.';
        }
        if (strlen($pass) < 10 || !preg_match('/[A-Za-z]/', $pass) || !preg_match('/\d/', $pass)) {
            $errors['admin_password'] = 'Use at least 10 characters including letters and numbers.';
        } elseif ($pass !== (string) ($_POST['admin_password_confirmation'] ?? '')) {
            $errors['admin_password_confirmation'] = 'Passwords do not match.';
        }

        if ($state['needs_config']) {
            $host = $in('db_host') ?: 'localhost';
            $port = (int) ($in('db_port') ?: 3306);
            $db = $in('db_name');
            $user = $in('db_user');
            $dbPass = (string) ($_POST['db_pass'] ?? '');
            $baseUrl = rtrim($in('base_url'), '/');
            if (!preg_match('/^[A-Za-z0-9_\-]{1,64}$/', $db)) {
                $errors['db_name'] = 'Enter the database name exactly as shown in cPanel.';
            }
            if ($user === '' || strlen($user) > 80) {
                $errors['db_user'] = 'Enter the database user.';
            }
            if (!preg_match('/^[A-Za-z0-9.\-]+$/', $host)) {
                $errors['db_host'] = 'Enter a valid host (usually localhost).';
            }
            if (!filter_var($baseUrl, FILTER_VALIDATE_URL) || !preg_match('#^https?://#', $baseUrl)) {
                $errors['base_url'] = 'Enter the full website address, e.g. https://journzey.ai';
            }
            if (!$errors) {
                try {
                    $pdo = new PDO("mysql:host=$host;port=$port;dbname=$db;charset=utf8mb4", $user, $dbPass, [
                        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC, PDO::ATTR_EMULATE_PREPARES => false,
                        PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci, time_zone = '+00:00'",
                    ]);
                } catch (\PDOException $e) {
                    $errors['db'] = 'Could not connect to the database. Check the host, name, user and password, and that the user has ALL PRIVILEGES on the database.';
                }
            }
            if (!$errors && !is_writable(ROOT_PATH . '/config')) {
                $errors['db'] = 'The config/ folder is not writable. Set its permissions to 755 (or create config/config.php manually from config/config.example.php).';
            }
            if ($errors) {
                $this->view(['state' => $state, 'errors' => $errors, 'old' => $old]);
            }
            try {
                if (!self::tableExists($pdo, 'settings')) {
                    self::importSql($pdo, (string) file_get_contents(ROOT_PATH . '/database.sql'));
                }
            } catch (\Throwable $e) {
                \App\Core\Logger::error('Installer SQL import failed: ' . $e->getMessage());
                $this->view(['state' => $state, 'errors' => ['db' => 'Importing database.sql failed. Make sure the database is empty, or import database.sql with phpMyAdmin and run /setup again.'], 'old' => $old]);
            }
            $key = bin2hex(random_bytes(32));
            $cfg = "<?php\n// Generated by the journzey.ai installer on " . gmdate('Y-m-d H:i') . " UTC. Keep this file private and backed up.\n"
                . 'define(\'DB_HOST\', ' . var_export($host, true) . ");\n"
                . 'define(\'DB_PORT\', ' . $port . ");\n"
                . 'define(\'DB_NAME\', ' . var_export($db, true) . ");\n"
                . 'define(\'DB_USER\', ' . var_export($user, true) . ");\n"
                . 'define(\'DB_PASS\', ' . var_export($dbPass, true) . ");\n"
                . 'define(\'BASE_URL\', ' . var_export($baseUrl, true) . ");\n"
                . 'define(\'APP_KEY\', ' . var_export($key, true) . ");\n"
                . "define('APP_ENV', 'production');\ndefine('APP_DEBUG', false);\n";
            if (file_put_contents(CONFIG_FILE, $cfg, LOCK_EX) === false) {
                $this->view(['state' => $state, 'errors' => ['db' => 'Could not write config/config.php. Check folder permissions.'], 'old' => $old]);
            }
            @chmod(CONFIG_FILE, 0640);
            Database::connectWith($pdo);
        } else {
            if ($errors) {
                $this->view(['state' => $state, 'errors' => $errors, 'old' => $old]);
            }
            if (!$state['tables']) {
                self::importSql(Database::pdo(), (string) file_get_contents(ROOT_PATH . '/database.sql'));
            }
        }

        $roleId = (int) Database::value("SELECT id FROM roles WHERE slug = 'super-admin'");
        Database::insert('admins', ['role_id' => $roleId ?: 1, 'name' => $name, 'email' => $email, 'password_hash' => password_hash($pass, PASSWORD_DEFAULT), 'status' => 'active']);
        Database::query("INSERT INTO settings (`key`, `value`, group_name) VALUES ('contact_email', :e, 'general') ON DUPLICATE KEY UPDATE `value` = IF(`value` = '' OR `value` IS NULL, VALUES(`value`), `value`)", ['e' => $email]);
        file_put_contents(INSTALL_LOCK, gmdate('c'));
        $this->view(['state' => ['done' => true], 'errors' => [], 'old' => [], 'adminUrl' => isset($baseUrl) ? $baseUrl . '/' . ADMIN_PREFIX . '/login' : admin_url('login')]);
    }

    private function guard(): void
    {
        if (is_file(INSTALL_LOCK) && APP_CONFIGURED) {
            Response::abort(404);
        }
    }

    private function state(): array
    {
        $s = ['needs_config' => !APP_CONFIGURED, 'tables' => false, 'admins' => 0, 'db_error' => false, 'done' => false];
        $s['requirements'] = [
            'PHP 8.1 or newer' => version_compare(PHP_VERSION, '8.1.0', '>='),
            'PDO MySQL extension' => extension_loaded('pdo_mysql'),
            'GD extension (image processing)' => extension_loaded('gd'),
            'Sodium extension (encryption)' => extension_loaded('sodium'),
            'Fileinfo extension (upload checks)' => extension_loaded('fileinfo'),
            'mbstring extension' => extension_loaded('mbstring'),
            'config/ folder writable' => is_writable(ROOT_PATH . '/config') || APP_CONFIGURED,
            'storage/ folder writable' => is_writable(STORAGE_PATH),
            'uploads/ folder writable' => is_writable(UPLOAD_PATH),
        ];
        if (APP_CONFIGURED) {
            try {
                $s['tables'] = self::tableExists(Database::pdo(), 'settings');
                $s['admins'] = $s['tables'] ? (int) Database::value('SELECT COUNT(*) FROM admins') : 0;
            } catch (\Throwable $e) {
                $s['db_error'] = true;
            }
        }
        return $s;
    }

    private function view(array $data): never
    {
        $GLOBALS['__errors'] = $data['errors'];
        $GLOBALS['__old'] = $data['old'];
        View::show('setup/index', $data, null, $data['errors'] ? 422 : 200);
    }

    private static function tableExists(PDO $pdo, string $table): bool
    {
        $st = $pdo->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = DATABASE() AND table_name = ?');
        $st->execute([$table]);
        return (int) $st->fetchColumn() > 0;
    }

    /** Splits a SQL dump into statements (respecting quotes and comments) and runs them. */
    public static function importSql(PDO $pdo, string $sql): void
    {
        $stmts = [];
        $buf = '';
        $len = strlen($sql);
        $quote = null;
        for ($i = 0; $i < $len; $i++) {
            $c = $sql[$i];
            if ($quote === null) {
                if ($c === '-' && ($sql[$i + 1] ?? '') === '-' && ($i === 0 || $sql[$i - 1] === "\n")) {
                    $nl = strpos($sql, "\n", $i);
                    $i = $nl === false ? $len : $nl;
                    continue;
                }
                if ($c === "'" || $c === '"' || $c === '`') {
                    $quote = $c;
                } elseif ($c === ';') {
                    if (trim($buf) !== '') {
                        $stmts[] = $buf;
                    }
                    $buf = '';
                    continue;
                }
            } elseif ($c === '\\' && $quote !== '`') {
                $buf .= $c . ($sql[$i + 1] ?? '');
                $i++;
                continue;
            } elseif ($c === $quote) {
                if (($sql[$i + 1] ?? '') === $quote) {
                    $buf .= $c . $c;
                    $i++;
                    continue;
                }
                $quote = null;
            }
            $buf .= $c;
        }
        if (trim($buf) !== '') {
            $stmts[] = $buf;
        }
        foreach ($stmts as $st) {
            $pdo->exec($st);
        }
    }
}
