<?php
declare(strict_types=1);

namespace App\Controllers;

use App\Core\Request;
use App\Trading\FlexCard;

/** Public page behind the QR code on a daily flex card: confirms the card came from a journzey.ai journal. */
final class VerifyController extends Controller
{
    public function show(Request $req): never
    {
        $card = FlexCard::find((string) ($req->params['code'] ?? ''));
        if (!$card) {
            $this->notFound();
        }
        header('X-Robots-Tag: noindex, nofollow');
        $this->render('verify', ['card' => $card['payload'], 'checked' => $card['updated_at']], [
            'title' => 'Verified trading day card', 'description' => 'This trading day card was generated by journzey.ai from the trader’s journal.', 'path' => '/verify/' . $req->params['code'], 'noindex' => true,
        ]);
    }
}
