<?php
/** @var array $card @var string $checked */
$c = $card; $up = (float) $c['net'] >= 0;
?>
<section class="section section-tight">
  <div class="container verify-wrap">
    <div class="verify-card <?= $up ? 'is-up' : 'is-down' ?>">
      <div class="verify-badge"><?= icon('check-circle', 'icon') ?> Verified by <?= e(setting('site_name', 'journzey.ai')) ?></div>
      <p class="verify-date"><?= e($c['date_label']) ?><?= $c['name'] !== '' ? ' · ' . e($c['name']) : '' ?><?= !empty($c['demo']) ? ' · <strong>DEMO DATA</strong>' : '' ?></p>
      <p class="verify-pnl <?= $up ? 'up' : 'down' ?>"><?= e(money($c['net'], $c['currency'], true)) ?></p>
      <dl class="verify-stats">
        <div><dt>Trades</dt><dd><?= (int) $c['trades'] ?> (<?= (int) $c['wins'] ?>W · <?= (int) $c['losses'] ?>L)</dd></div>
        <div><dt>Win rate</dt><dd><?= e(pct($c['win_rate'], 0)) ?></dd></div>
        <?php if ($c['total_r'] !== null): ?><div><dt>Total R</dt><dd><?= e(($c['total_r'] > 0 ? '+' : '') . number_format((float) $c['total_r'], 2)) ?>R</dd></div><?php endif; ?>
        <?php if ($c['discipline'] !== null): ?><div><dt>Discipline score</dt><dd><?= e((string) $c['discipline']) ?>/10</dd></div><?php endif; ?>
        <?php if (!empty($c['emotions'])): ?><div><dt>Emotions</dt><dd><?= e(implode(', ', $c['emotions'])) ?></dd></div><?php endif; ?>
      </dl>
      <p class="verify-note">This card was generated by <?= e(setting('site_name', 'journzey.ai')) ?> from the trader’s own journal (<?= e(strtolower($c['account_type'])) ?>) and matches it as of <?= e(fmt_date($checked, 'M j, Y H:i')) ?> UTC. Trades are recorded by the trader; they are not confirmed with a broker. Past results do not guarantee future results.</p>
      <a class="btn btn-primary" href="<?= e(url('/signup')) ?>">Start your own trading journal</a>
    </div>
  </div>
</section>
