<?php
/** @var array $card @var string $checked */
$c = $card; $isTrade = ($c['kind'] ?? 'day') === 'trade'; $up = (float) ($isTrade ? $c['pnl'] : $c['net']) >= 0;
?>
<section class="section section-tight">
  <div class="container verify-wrap">
    <div class="verify-card <?= $up ? 'is-up' : 'is-down' ?>">
      <div class="verify-badge"><?= icon('check-circle', 'icon') ?> Verified by <?= e(setting('site_name', 'journzey.ai')) ?></div>
      <p class="verify-date"><?= e($c['date_label']) ?><?= $c['name'] !== '' ? ' · ' . e($c['name']) : '' ?><?= !empty($c['demo']) ? ' · <strong>DEMO DATA</strong>' : '' ?></p>
      <?php if ($isTrade): ?>
      <p class="verify-sym"><strong><?= e($c['symbol']) ?></strong> <span class="badge <?= $c['side'] === 'LONG' ? 'st-published' : 'st-warn' ?>"><?= $c['side'] === 'LONG' ? 'BUY' : 'SELL' ?></span></p>
      <p class="verify-pnl <?= $up ? 'up' : 'down' ?>"><?= e(money($c['pnl'], $c['currency'], true)) ?></p>
      <dl class="verify-stats">
        <?php if ($c['r'] !== null): ?><div><dt>R multiple</dt><dd><?= e(($c['r'] > 0 ? '+' : '') . number_format((float) $c['r'], 2)) ?>R</dd></div><?php endif; ?>
        <div><dt>Entry</dt><dd><?= e((string) ($c['entry'] ?? '—')) ?></dd></div>
        <div><dt>Exit</dt><dd><?= e((string) ($c['exit'] ?? '—')) ?></dd></div>
        <div><dt>Lot size</dt><dd><?= e((string) ($c['lots'] ?? '—')) ?></dd></div>
        <?php if (!empty($c['strategy'])): ?><div><dt>Strategy</dt><dd><?= e($c['strategy']) ?></dd></div><?php endif; ?>
        <?php if (!empty($c['session'])): ?><div><dt>Session</dt><dd><?= e($c['session']) ?></dd></div><?php endif; ?>
      </dl>
      <?php else: ?>
      <p class="verify-pnl <?= $up ? 'up' : 'down' ?>"><?= e(money($c['net'], $c['currency'], true)) ?></p>
      <dl class="verify-stats">
        <div><dt>Trades</dt><dd><?= (int) $c['trades'] ?> (<?= (int) $c['wins'] ?>W · <?= (int) $c['losses'] ?>L)</dd></div>
        <div><dt>Win rate</dt><dd><?= e(pct($c['win_rate'], 0)) ?></dd></div>
        <?php if ($c['total_r'] !== null): ?><div><dt>Total R</dt><dd><?= e(($c['total_r'] > 0 ? '+' : '') . number_format((float) $c['total_r'], 2)) ?>R</dd></div><?php endif; ?>
        <?php if ($c['discipline'] !== null): ?><div><dt>Discipline score</dt><dd><?= e((string) $c['discipline']) ?>/10</dd></div><?php endif; ?>
        <?php if (!empty($c['emotions'])): ?><div><dt>Emotions</dt><dd><?= e(implode(', ', $c['emotions'])) ?></dd></div><?php endif; ?>
      </dl>
      <?php endif; ?>
      <p class="verify-note">This card was generated by <?= e(setting('site_name', 'journzey.ai')) ?> from the trader’s own journal (<?= e(strtolower($c['account_type'])) ?>) and matches it as of <?= e(fmt_date($checked, 'M j, Y H:i')) ?> UTC. Trades are recorded by the trader; they are not confirmed with a broker. Past results do not guarantee future results.</p>
      <a class="btn btn-primary" href="<?= e(url('/signup')) ?>">Start your own trading journal</a>
    </div>
  </div>
</section>
